# Generated by Django 2.0.7 on 2018-07-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aafinder', '0002_add_default_meeting_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='orig_filename',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='row_src',
            field=models.TextField(blank=True),
        ),
    ]
