# Generated by Django 2.0.7 on 2018-07-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aafinder', '0003_auto_20180713_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingarea',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingtype',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
